name: Generate CI Docs
on:
  push:
    paths:
      - '.github/workflows/**'
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build pipedoc
        run: go build -o pipedoc ./cmd/pipedoc/main.go

      - name: Run pipedoc
        run: ./pipedoc -f .github/workflows/ci.yml -o docs/ci-pipeline.md

      - name: Upload CI Docs as artefact
        uses: actions/upload-artifact@v4
        with:
          name: ci-pipeline-docs
          path: |
            docs/ci-pipeline.md
            docs/ci-pipeline.mmd
