name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  docker:
    name: Build & Push Multi-Arch Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/pipedoc
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:${GITHUB_REF_NAME} \
            -t $IMAGE_NAME:latest \
            --push .

  go-binaries:
    name: Build Go Binaries and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/pipedoc-linux-amd64 ./cmd/pipedoc
          GOOS=linux GOARCH=arm64 go build -o dist/pipedoc-linux-arm64 ./cmd/pipedoc
          GOOS=darwin GOARCH=amd64 go build -o dist/pipedoc-darwin-amd64 ./cmd/pipedoc
          GOOS=darwin GOARCH=arm64 go build -o dist/pipedoc-darwin-arm64 ./cmd/pipedoc
          GOOS=windows GOARCH=amd64 go build -o dist/pipedoc-windows-amd64.exe ./cmd/pipedoc

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            ## Changes
            - Multi-arch Docker image for amd64 + arm64
            - Prebuilt binaries for Linux, macOS (Intel + M1/M2), and Windows
          files: |
            dist/pipedoc-linux-amd64
            dist/pipedoc-linux-arm64
            dist/pipedoc-darwin-amd64
            dist/pipedoc-darwin-arm64
            dist/pipedoc-windows-amd64.exe
